[package]
name = "basset"
version = "0.1.0"
authors = ["MSNTCS <najafi@codechain.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = ["cranelift"]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]
cranelift = ["cosmwasm-vm/default-cranelift"]
singlepass = ["cosmwasm-vm/default-singlepass"]

[dependencies]
cw20 = { version = "0.6.0" }
cosmwasm-storage = { version = "0.10.1" }
terra-cosmwasm = { version = "2.0.0" }
cosmwasm-std = { version = "0.14.0" }
schemars = "0.8"
thiserror = { version = "1.0.20" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-vm = { version = "0.10.1", default-features = false }
